services:
  omx-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CODEX_NPM_TAG: ${CODEX_NPM_TAG:-latest}
        OMX_NPM_TAG: ${OMX_NPM_TAG:-latest}
        NPM_REFRESH: ${NPM_REFRESH:-0}
    image: industrial-ai-omx-sandbox:latest
    working_dir: /workspace
    stdin_open: true
    tty: true
    group_add:
      - "0"
    environment:
      CODEX_HOME: /home/dev/.codex
      SSH_AUTH_SOCK: /ssh-agent
      GIT_USER_NAME: Heewon Yun
      GIT_USER_EMAIL: yun.heewon0909@gmail.com
    volumes:
      - ./:/workspace
      - ${HOME}/.codex:/host-codex:ro
      - omx-codex-home:/home/dev/.codex
      - ${SSH_AUTH_SOCK}:/ssh-agent
    command: ["bash"]

volumes:
  omx-codex-home:
